name             'main'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'MIT'
description      'Installs/Configures main'
long_description 'Installs/Configures main'
version          '0.1.1'

depends 'apt', '~> 5.0.1'
depends 'docker', '~> 2.13.9'
