name             'main'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures main'
long_description 'Installs/Configures main'
version          '0.1.0'

depends 'apt', '~> 3.0.0'
depends 'docker', '~> 2.6.8'
